# Generated by Django 3.0.5 on 2020-04-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/<django.db.models.query_utils.DeferredAttribute object at 0x0000019CFFF05EE0>%Y%m%d/'),
        ),
    ]
